import request from "supertest";
import app from "../src/index";

describe("GET /wine", () => {
    describe("Getting wine and wines by queries", () => {
        it("should return one wine by title", async () => {
            request(app)
                .get("/wine?title=Thanisch Hochgewächs Riesling 2020")
                .expect("Content-Type", "application/json; charset=utf-8")
                .expect({
                    id: "ed12ef3e-c79d-4b72-bf8c-1f69602c3fb0",
                    createdAt: "2022-02-22 14:47:24.018626",
                    updatedAt: "2022-02-22 19:58:58.423352",
                    deletedAt: "",
                    version: "2",
                    title: "Thanisch Hochgewächs Riesling 2020",
                    color: "white",
                    ean: "4260126992009",
                    type: "wine",
                    country: "DE",
                    region: "Mosel",
                    currency: "EUR",
                    status: "published",
                    imageUrl: "https://www.ebrosia.de/media/image/f8/50/4a/013764_Thanisch-Hochgewaechs-Riesling.png",
                    producer: "Thanisch",
                    vintage: "2020",
                    rrp: "17.85",
                    highestPrice: "16",
                    lowestPrice: "10",
                    gallery: "",
                    description:
                        "Fließt der Riesling mit seinem hellen Gelb in das Glas, bringt er eine fruchtige Aromatik nach Zitrusfrüchten und reifen Äpfeln hervor. Der saftige und ausgereifte Körper umarmt die deutliche Restsüße und lässt sie auf eine angenehme Säure treffen. Der Nachhall des Weins ist unglaublich großartig fruchtig und dabei lange ausklingend.",
                    bottleSize: "0.75",
                    category: "",
                    grapes: "Riesling",
                    closure: "screw cork",
                    sweetness: "sweet",
                    bio: "",
                    vegan: "",
                    storageType: "",
                    alcoholPercentage: "",
                    sugarLevel: "",
                })
                .expect(200);
        });

        it("should return 400 missing query", async () => {
            request(app).get("/wine").expect(400);
        });

        it("should return wine list by country", async () => {
            request(app)
                .get("/wine?country=DE")
                .expect("Content-Type", "application/json; charset=utf-8")
                .expect(200)
                .expect([
                    {
                        id: "0819c302-6166-40ba-b3b2-e51470585fe2",
                        createdAt: "2022-02-22 14:47:13.159092",
                        updatedAt: "2022-02-22 14:47:13.159092",
                        deletedAt: "",
                        version: "1",
                        title: "Schröder & Schÿler Sauternes AOC 0,5l 2018",
                        color: "white",
                        ean: "3263070041015",
                        type: "wine",
                        country: "TR",
                        region: "Bordeaux",
                        currency: "EUR",
                        status: "published",
                        imageUrl: "https://www.ebrosia.de/media/image/60/e4/c0/002521_Schroeder-Schyler-Sauternes_l.png",
                        producer: "Schröder & Schÿler",
                        vintage: "2018",
                        rrp: "17.85",
                        highestPrice: "15",
                        lowestPrice: "10",
                        gallery: "",
                        description:
                            "Bestellen Sie jetzt günstig bei ebrosia einen exzellenten Sauternes Süßwein aus dem Bordeaux. Fruchtig in der Nase, streicht er reich und süß über den Gaumen. Besondere kulinarische Harmonien geht er zusammen mit Edelschimmelkäse wie Roquefort oder Gorgonzola ein. Klassisch genießt man einen französischen Sauternes zu französischer Foie Gras!",
                        bottleSize: "0.5",
                        category: "",
                        grapes: "Muscadelle, Sauvignon Blanc, Sémillon",
                        closure: "nature cork",
                        sweetness: "sweet",
                        bio: "",
                        vegan: "",
                        storageType: "",
                        alcoholPercentage: "",
                        sugarLevel: "",
                    },
                ]);
        });

        it("should return wine list by color", async () => {
            request(app)
                .get("/wine?color=black")
                .expect("Content-Type", "application/json; charset=utf-8")
                .expect(200)
                .expect([
                    {
                        id: "b1bfad8f-ce73-4b1d-9343-e69cd1374187",
                        createdAt: "2022-02-22 14:47:12.885723",
                        updatedAt: "2022-02-22 14:47:12.885723",
                        deletedAt: "",
                        version: "1",
                        title: "San Marzano Primitivo di Manduria Sessantanni DOC 2017",
                        color: "black",
                        ean: "8023354133714",
                        type: "wine",
                        country: "IT",
                        region: "Apulien",
                        currency: "EUR",
                        status: "published",
                        imageUrl: "https://www.ebrosia.de/media/image/02/b8/0a/008785_Sessantani-Primitivo-di-Manduria-DOC_l.png",
                        producer: "Cantine San Marzano",
                        vintage: "2017",
                        rrp: "17.85",
                        highestPrice: "15",
                        lowestPrice: "10",
                        gallery: "",
                        description:
                            "Sessantanni Primitivo di Manduria: Komplexes und fruchtiges Bouquet mit Aromen von Kirschenkonfitüre, Zwetschgen, Tabakblättern, Kakao und Vanille, das sich in einen außergwöhnlich samtigen und zugleich wuchtigen Körper von unglaublicher Länge bettet. Weinkritiker, Fachwelt und Weingenießer sind sich im Falle des Sessantanni einig: Ein Monument der Rebsorte Primitivo!",
                        bottleSize: "0.75",
                        category: "",
                        grapes: "Primitivo",
                        closure: "nature cork",
                        sweetness: "dry",
                        bio: "",
                        vegan: "",
                        storageType: "",
                        alcoholPercentage: "",
                        sugarLevel: "",
                    },
                ]);
        });
    });

    describe("Getting related wine list", () => {
        it("should return related wines by id", async () => {
            request(app)
                .get("/wine/6007070a-678b-4ebb-892a-a262204e5204/related")
                .expect("Content-Type", "application/json; charset=utf-8")
                .expect(200)
                .expect([
                    {
                        id: "6007070a-678b-4ebb-892a-a262204e5204",
                        createdAt: "2022-02-22 14:47:12.998494",
                        updatedAt: "2022-02-22 14:47:12.998494",
                        deletedAt: "",
                        version: "1",
                        title: "Hugl-Wimmer Grüner Veltliner 1,0l 2020",
                        color: "white",
                        ean: "9120031480211",
                        type: "wine",
                        country: "AT",
                        region: "Niederösterreich",
                        currency: "EUR",
                        status: "published",
                        imageUrl: "https://www.ebrosia.de/media/image/10/95/0f/004348_Weingut-Hugl-Guener-Veltliner_2012_l.png",
                        producer: "Hugl-Wimmer",
                        vintage: "2020",
                        rrp: "17.85",
                        highestPrice: "15",
                        lowestPrice: "10",
                        gallery: "",
                        description:
                            "Die beliebte österreichische Sorte Grüner Veltliner zählt zu den besten Trauben der Welt! Dieser frisch fruchtige Grüne Veltliner ist genau der richtige Wein, wenn zartes Geflügel, ein fein gewürztes Fischfilet oder das berühmte Wiener Schnitzel auf dem Teller liegen. Der leicht pfeffrige Geschmack, wofür der Grüne Veltliner seine weltweite Berühmtheit erlangt hat und sein dezent würziger Abgang begleiten viele leichte Speisen. Probieren Sie diesen idealen Tischwein des jungen Martin Hugl!",
                        bottleSize: "1",
                        category: "",
                        grapes: "Grüner Veltliner",
                        closure: "screw cork",
                        sweetness: "dry",
                        bio: "",
                        vegan: "",
                        storageType: "",
                        alcoholPercentage: "",
                        sugarLevel: "",
                    },
                    {
                        id: "d6f21e5c-53f0-4846-8b9b-618e8356b170",
                        createdAt: "2022-02-22 14:47:14.464524",
                        updatedAt: "2022-02-22 14:47:14.464524",
                        deletedAt: "",
                        version: "1",
                        title: "Hugl-Wimmer Grüner Veltliner Poysdorfer Saurüssel 2020",
                        color: "white",
                        ean: "9120031480310",
                        type: "wine",
                        country: "AT",
                        region: "Niederösterreich",
                        currency: "EUR",
                        status: "published",
                        imageUrl: "https://www.ebrosia.de/media/image/39/20/70/008218_Wimmer-Hugl-Poysdorfer-Sauruessel_l.png",
                        producer: "Hugl-Wimmer",
                        vintage: "2020",
                        rrp: "17.85",
                        highestPrice: "15",
                        lowestPrice: "10",
                        gallery: "",
                        description:
                            "Der legendäre Weißwein vom Weingut Hugl-Wimmer aus Niederösterreich knüpft an den Erfolg aus den 70er und 80er Jahren an. Durch das Engagement lokaler Winzer ist dieser leichte Wein mit nur 11,5% Alkohol zum Mega-Erfolg geworden. Ein fruchtiger Trend aus Österreich.",
                        bottleSize: "0.75",
                        category: "",
                        grapes: "Grüner Veltliner",
                        closure: "screw cork",
                        sweetness: "dry",
                        bio: "",
                        vegan: "",
                        storageType: "",
                        alcoholPercentage: "",
                        sugarLevel: "",
                    },
                    {
                        id: "3013e6a3-544a-4221-880f-9e9e642055bf",
                        createdAt: "2022-02-22 14:47:14.540853",
                        updatedAt: "2022-02-22 14:47:14.540853",
                        deletedAt: "",
                        version: "1",
                        title: "Hugl-Wimmer Grüner Veltliner Weinviertel DAC 2020",
                        color: "white",
                        ean: "9120031480426",
                        type: "wine",
                        country: "AT",
                        region: "Weinviertel",
                        currency: "EUR",
                        status: "published",
                        imageUrl: "https://www.ebrosia.de/media/image/a5/2a/bd/008468_Hugl-Wimmer-Gruener-Veltliner_l.png",
                        producer: "Hugl-Wimmer",
                        vintage: "2020",
                        rrp: "17.85",
                        highestPrice: "15",
                        lowestPrice: "10",
                        gallery: "",
                        description:
                            "Entdecken Sie ausgezeichneten Grünen Veltliner Weinviertel DAC vom Weingut Hugl-Wimmer. Die Veltliner Rebe ist die wichtigste und bekannteste weiße Rebsorte Österreichs (auch Weißgipfler genannt), wo sie optimale Klimavoraussetzungen und Böden findet. Fast 1/3 Österreichs Weinberge sind mit dieser Rebe bestockt. Ein Paradebeispiel für einen guten Veltliner zeigt das Weingut Hugl-Wimmer mit seinem Wein aus dem Weinviertel, dessen Ausbauform die Herkunftsregion in den Mittelpunkt stellt. Der als DAC zertifizierte Wein wurde in einer Blindverkostung von einer staatlich geprüften Jury dafür verkostet und zertifiziert.",
                        bottleSize: "0.75",
                        category: "",
                        grapes: "Grüner Veltliner",
                        closure: "screw cork",
                        sweetness: "dry",
                        bio: "",
                        vegan: "",
                        storageType: "",
                        alcoholPercentage: "",
                        sugarLevel: "",
                    },
                    {
                        id: "8da1256c-8ac4-456d-a0ab-4d1d71a93dae",
                        createdAt: "2022-02-22 14:47:14.672681",
                        updatedAt: "2022-02-22 14:47:14.672681",
                        deletedAt: "",
                        version: "1",
                        title: "Wimmer Grüner Veltliner 2020",
                        color: "white",
                        ean: "9120031480372",
                        type: "wine",
                        country: "AT",
                        region: "Niederösterreich",
                        currency: "EUR",
                        status: "published",
                        imageUrl: "https://www.ebrosia.de/media/image/c1/g0/6c/007969_Hugl-Wimmer-Gruener-Veltliner_l.png",
                        producer: "Hugl-Wimmer",
                        vintage: "2020",
                        rrp: "17.85",
                        highestPrice: "15",
                        lowestPrice: "10",
                        gallery: "",
                        description:
                            "Grüner Veltliner aus Österreich gehört mit seinem typischen Pfefferl zur Weltspitze! Und das zurecht, wie der geneigte Weinfreund zugeben muss. Denn ein Grüner Veltliner ist stets wie Musik am Gaumen. Sein frischer Duft von saftigem Pfirsich und Limone stimmt harmonisch auf den Gaumen ein. Hier setzt das berühmte österreichische Pfefferl fein-würzige Akzente. Frisch, fruchtig und anhaltend lang ist das Finale dieses köstlichen Veltliners.",
                        bottleSize: "0.75",
                        category: "",
                        grapes: "Grüner Veltliner",
                        closure: "screw cork",
                        sweetness: "dry",
                        bio: "",
                        vegan: "",
                        storageType: "",
                        alcoholPercentage: "",
                        sugarLevel: "",
                    },
                    {
                        id: "8b7125e6-6c02-4f73-8df8-2a94059643ed",
                        createdAt: "2022-02-22 14:47:15.618578",
                        updatedAt: "2022-02-22 14:47:15.618578",
                        deletedAt: "",
                        version: "1",
                        title: "Zahel Grüner Veltliner Niederösterreich 2017",
                        color: "white",
                        ean: "9007940003079",
                        type: "wine",
                        country: "AT",
                        region: "Niederösterreich",
                        currency: "EUR",
                        status: "published",
                        imageUrl: "https://www.ebrosia.de/media/image/63/9c/07/009672_Zahel-Gruener-Veltliner_l.png",
                        producer: "Zahel",
                        vintage: "2017",
                        rrp: "17.85",
                        highestPrice: "15",
                        lowestPrice: "10",
                        gallery: "",
                        description:
                            "Genießen Sie vom Weingut Zahel Grüner Veltliner aus Niederösterreich. Der Wein zeigt sich hellgolden, mit zart grünlichen Reflexen im Glas. Der jugendlich-fruchtige Geruch nach grünem Apfel und tropischen Früchten wird begleitet von würzigen Noten und einer Nuance Waldboden. Am Gaumen ist der Veltliner angenehm trocken, voller Lebendigkeit und geprägt von einem fruchtigen Charakter, sowie Noten von Wiesen-Kräutern. Die Säure ist gut eingebunden und der Nachhall von einer grandiosen Mineralik geprägt.",
                        bottleSize: "0.75",
                        category: "",
                        grapes: "Grüner Veltliner",
                        closure: "screw cork",
                        sweetness: "dry",
                        bio: "",
                        vegan: "",
                        storageType: "",
                        alcoholPercentage: "",
                        sugarLevel: "",
                    },
                    {
                        id: "7a50f513-b003-490c-8084-2be66cf9a12d",
                        createdAt: "2022-02-22 14:47:20.154889",
                        updatedAt: "2022-02-22 14:47:20.154889",
                        deletedAt: "",
                        version: "1",
                        title: "Nittnaus Grüner Veltliner Selection 2020",
                        color: "white",
                        ean: "9120007311037",
                        type: "wine",
                        country: "AT",
                        region: "Burgenland",
                        currency: "EUR",
                        status: "published",
                        imageUrl: "https://www.ebrosia.de/media/image/e5/39/98/012459_Nittnaus-Gruener-Veltliner-Selection_l.png",
                        producer: "Nittnaus",
                        vintage: "2020",
                        rrp: "17.85",
                        highestPrice: "15",
                        lowestPrice: "10",
                        gallery: "",
                        description:
                            "Der hellgelbe Grüne Veltliner Selection begeistert optisch mit grünen Reflexen. Im Bouquet begeistern Aromen heimischer Früchte, der saftige Gaumen ist von gelber Frucht stark geprägt.",
                        bottleSize: "0.75",
                        category: "",
                        grapes: "Grüner Veltliner",
                        closure: "screw cork",
                        sweetness: "dry",
                        bio: "",
                        vegan: "",
                        storageType: "",
                        alcoholPercentage: "",
                        sugarLevel: "",
                    },
                    {
                        id: "d8ce73f0-d2d7-444c-b91c-b8a70e9a915c",
                        createdAt: "2022-02-22 14:47:21.122141",
                        updatedAt: "2022-02-22 14:47:21.122141",
                        deletedAt: "",
                        version: "1",
                        title: "Schmelzer Grüner Veltliner Heideboden 2019",
                        color: "white",
                        ean: "9120026710095",
                        type: "wine",
                        country: "AT",
                        region: "Burgenland",
                        currency: "EUR",
                        status: "published",
                        imageUrl: "https://www.ebrosia.de/media/image/f8/f6/aa/012939_Schmelzer-Gruener-Veltiner.png",
                        producer: "Schmelzer",
                        vintage: "2019",
                        rrp: "17.85",
                        highestPrice: "15",
                        lowestPrice: "10",
                        gallery: "",
                        description:
                            "Helle Gelb mit ganz zarten grünen Reflexen blitzt aus dem Glas. Das Aroma erinnert an grünen Apfel und exotische Früchte wie Papaya und Mango. Am Gaumen zeigt sich die Würze animierend und wird von einem ausgewogenen Süße-Säure-Spiel begleitet. Lang und Vorfreude-weckend klingt der Weißwein aus.",
                        bottleSize: "0.75",
                        category: "",
                        grapes: "Grüner Veltliner",
                        closure: "screw cork",
                        sweetness: "dry",
                        bio: "",
                        vegan: "",
                        storageType: "",
                        alcoholPercentage: "",
                        sugarLevel: "",
                    },
                    {
                        id: "13b8282d-d56c-4e58-91c8-c92b128395cd",
                        createdAt: "2022-02-22 14:47:22.382335",
                        updatedAt: "2022-02-22 14:47:22.382335",
                        deletedAt: "",
                        version: "1",
                        title: "Zahel Grüner Veltliner Bio 2020",
                        color: "white",
                        ean: "9007940003970",
                        type: "wine",
                        country: "AT",
                        region: "Niederösterreich",
                        currency: "EUR",
                        status: "published",
                        imageUrl: "https://www.ebrosia.de/media/image/b2/f8/00/013674_Zahel-Gruener-Veltliner-BIO_mockupXAXHbU1HLFrQ4.png",
                        producer: "Zahel",
                        vintage: "2020",
                        rrp: "17.85",
                        highestPrice: "15",
                        lowestPrice: "10",
                        gallery: "",
                        description:
                            "Genießen Sie vom Weingut Zahel Grüner Veltliner aus Niederösterreich. Der Wein zeigt sich hellgolden, mit zart grünlichen Reflexen im Glas. Der jugendlich-fruchtige Geruch nach grünem Apfel und tropischen Früchten wird begleitet von würzigen Noten und einer Nuance Waldboden. Am Gaumen ist der Veltliner angenehm trocken, voller Lebendigkeit und geprägt von einem fruchtigen Charakter, sowie Noten von Wiesen-Kräutern. Die Säure ist gut eingebunden und der Nachhall von einer grandiosen Mineralik geprägt.",
                        bottleSize: "0.75",
                        category: "",
                        grapes: "Grüner Veltliner",
                        closure: "screw cork",
                        sweetness: "dry",
                        bio: "",
                        vegan: "",
                        storageType: "",
                        alcoholPercentage: "",
                        sugarLevel: "",
                    },
                    {
                        id: "bc4376e4-25a2-4259-a386-b11baf3bc313",
                        createdAt: "2022-02-22 14:47:23.655577",
                        updatedAt: "2022-02-22 14:47:23.655577",
                        deletedAt: "",
                        version: "1",
                        title: "Pfaffl Grüner Veltliner VOM HAUS 2020",
                        color: "white",
                        ean: "9006332187779",
                        type: "wine",
                        country: "AT",
                        region: "Niederösterreich",
                        currency: "EUR",
                        status: "published",
                        imageUrl: "https://www.ebrosia.de/media/image/4a/7c/37/011571_Pfaffl-Gruener-Veltliner_l.png",
                        producer: "Pfaffl",
                        vintage: "2020",
                        rrp: "17.85",
                        highestPrice: "15",
                        lowestPrice: "10",
                        gallery: "",
                        description:
                            "Dieser angenehmen Weißwein kommt in einem hellgelben Tropfen ins Glas, der grünliche Reflexe im Licht aufblitzen lässt. Der Duft eines aromatischen Apfelkorbes umhüllt die Nase, der beim Genuss von einem feinen Reigen reifer Zitrusfrüchte zu zarten Kräutern und einem Hauch von Pfeffer begleitet wird. Frisch und spritzig umspielt der Körper den Mund zum belebenden und animinierenden Säure-Süße-Spiel. Der Nachhall zeigt sich präzise und mit mittellangem Ausklang.",
                        bottleSize: "0.75",
                        category: "",
                        grapes: "Grüner Veltliner",
                        closure: "screw cork",
                        sweetness: "dry",
                        bio: "",
                        vegan: "",
                        storageType: "",
                        alcoholPercentage: "",
                        sugarLevel: "",
                    },
                    {
                        id: "f48606c2-63cc-422c-a59a-bd72e75ac4e8",
                        createdAt: "2022-02-22 14:47:23.693045",
                        updatedAt: "2022-02-22 14:47:23.693045",
                        deletedAt: "",
                        version: "1",
                        title: "Pfaffl Grüner Veltliner Weinviertel ZEISEN DAC 2020",
                        color: "white",
                        ean: "9006332201703",
                        type: "wine",
                        country: "AT",
                        region: "Weinviertel",
                        currency: "EUR",
                        status: "published",
                        imageUrl: "https://www.ebrosia.de/media/image/d6/d5/d4/011576_Pfaffl-Gruener-Veltliner-Zeiseneck_l.png",
                        producer: "Pfaffl",
                        vintage: "2020",
                        rrp: "17.85",
                        highestPrice: "15",
                        lowestPrice: "10",
                        gallery: "",
                        description:
                            "In einem hellen Gelb mit grünlichen Reflexen strahlt dieser Grüne Veltliner dem Genießer entgegen und verwöhnt schon im Duft mit reifen Äpfeln zu feinen Birnen. Zarte Zitrusnoten und ein Hauch von Pfeffer prickeln am Gaumen und sorgen mit Frische, Leichtigkeit und vollendeter Frucht für einen schwungvollen Körper. Die feine Säure zeigt sich harmonisch eingebunden, der Nachhall brilliert reich an Aromen und mit angenehmer Länge.",
                        bottleSize: "0.75",
                        category: "",
                        grapes: "Grüner Veltliner",
                        closure: "screw cork",
                        sweetness: "dry",
                        bio: "",
                        vegan: "",
                        storageType: "",
                        alcoholPercentage: "",
                        sugarLevel: "",
                    },
                    {
                        id: "f3d89531-ec2a-4d1b-8605-4e41d9817581",
                        createdAt: "2022-02-22 14:47:23.706894",
                        updatedAt: "2022-02-22 14:47:23.706894",
                        deletedAt: "",
                        version: "1",
                        title: "Pfaffl Grüner Veltliner Weinviertel HAID DAC 2020",
                        color: "white",
                        ean: "9006332202106",
                        type: "wine",
                        country: "AT",
                        region: "Weinviertel",
                        currency: "EUR",
                        status: "published",
                        imageUrl: "https://www.ebrosia.de/media/image/ca/3e/17/011577_Pfaffl-Gruener-Veltliner-Haidvierl_l.png",
                        producer: "Pfaffl",
                        vintage: "2020",
                        rrp: "17.85",
                        highestPrice: "15",
                        lowestPrice: "10",
                        gallery: "",
                        description:
                            "Ein hellgelbes Kleid mit grünlichen Reflexen zeigt dieser köstliche Weißwein im Glas, aus dem der feine Duft sonnenverwöhnter Orangen emporsteigt. Feine Noten von Zitrusfrüchten und zarte Pfeffertöne fügen sich am Gaumen hinzu und geben dem Körper Frische und Eleganz. Das verführerische Süße-Säure-Spiel lässt die lebendige Frucht hervortreten. Dabei versteht der aromatische Weißwein bis zum langen, feinen Nachhall aromatisch zu verwöhnen.",
                        bottleSize: "0.75",
                        category: "",
                        grapes: "Grüner Veltliner",
                        closure: "screw cork",
                        sweetness: "dry",
                        bio: "",
                        vegan: "",
                        storageType: "",
                        alcoholPercentage: "",
                        sugarLevel: "",
                    },
                ]);
        });

        it("should return 404 not found cause of invalid id", async () => {
            request(app).get("/wine/887657d2002f/related").expect("Content-Type", "text/html; charset=utf-8").expect(400);
        });

        it("should return 404 not found cause of no related wine", async () => {
            request(app).get("/wine/6a26d9f3-d710-4e74-9f39-3681a58a9880/related").expect("Content-Type", "text/html; charset=utf-8").expect(404);
        });
    });
});

afterAll((done) => {
    app.close(() => {
        done();
    });
});
